server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: ******// password of mysql
    url: jdbc:mysql://localhost:3306/login_register?allowPublicKeyRetrieval=true&useSSL=false
    username: ****** // username of mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ******@gmail.com  // email id of gmail account
    password: ********  // password of gmail account

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000